from flask import Flask, render_template, request, jsonify
from groq import Groq
import json
import re
app = Flask(__name__)
GROQ_API_KEY = "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"  
GROQ_MODEL = "llama-3.3-70b-versatile"
client = Groq(api_key=GROQ_API_KEY)
def summarize_notes(notes_text: str, style: str = "bullet", detail: str = "medium") -> dict:
    style_instructions = {
        "bullet": "structured bullet-point key takeaways",
        "executive": "a concise executive summary paragraph",
        "flashcards": "flashcard-style Q&A pairs for studying",
        "mindmap": "a hierarchical outline with main topics and subtopics"
    }
    detail_instructions = {
        "brief": "very concise, 3-5 key points only",
        "medium": "balanced coverage, 6-10 key points",
        "detailed": "comprehensive, capture all important details"
    }
    prompt = f"""You are an expert note-taking assistant and knowledge distiller.
Transform the following notes into {style_instructions.get(style, 'bullet points')}.
Level of detail: {detail_instructions.get(detail, 'medium')}.
NOTES:
{notes_text}
Return ONLY a valid JSON object (no markdown, no code fences) with this structure:
{ 
  "title": "<auto-generated descriptive title for these notes>",
  "subject_area": "<detected subject/topic area>",
  "word_count_original": <integer>,
  "word_count_summary": <integer>,
  "compression_ratio": "<e.g. 85% shorter>",
  "key_points": [
    "<key point 1>",
    "<key point 2>"
  ],
  "summary_paragraph": "<2-4 sentence summary of all the notes>",
  "flashcards": [
    { "question": "<question>", "answer": "<answer>"} 
  ],
  "important_terms": [
    { "term": "<term>", "definition": "<brief definition from the notes>"} 
  ],
  "action_items": ["<any action item or to-do found in notes>"],
  "mind_map": { 
    "main_topic": "<central topic>",
    "branches": [
      { "topic": "<branch topic>", "subtopics": ["<subtopic 1>", "<subtopic 2>"]} 
    ]
  } ,
  "difficulty_level": "BEGINNER|INTERMEDIATE|ADVANCED",
  "study_tips": ["<tip 1>", "<tip 2>"]
} """
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[{"role": "user", "content": prompt}],
    )
    content = response.choices[0].message.content
    content = re.sub(r"```(?:json)?", "", content).strip()
    return json.loads(content)
@app.route("/")
def index():
    return render_template("index.html")
@app.route("/summarize", methods=["POST"])
def summarize():
    data = request.json
    notes_text = data.get("text", "").strip()
    style = data.get("style", "bullet")
    detail = data.get("detail", "medium")
    if not notes_text:
        return jsonify({"error": "Please paste your notes."}), 400
    if len(notes_text) < 50:
        return jsonify({"error": "Notes are too short. Please provide more content."}), 400
    if len(notes_text) > 12000:
        notes_text = notes_text[:12000]
    try:
        result = summarize_notes(notes_text, style, detail)
        return jsonify(result)
    except json.JSONDecodeError:
        return jsonify({"error": "Failed to parse AI response. Please try again."}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500
if __name__ == "__main__":
    app.run(debug=True)
